name: Build and deploy frontend to qa

on:
  pull_request: { branches: ["zbmed-dev"] }
  push:
    branches: ['zbmed-dev']

env:
  KUBECONFIG: .kube/config
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: generate-image-tag
        name: Generate Image Tag
        env:
          ref_name: "${{ github.ref_name }}"
          head_ref: "${{ github.head_ref }}"
        run: |
          head_ref="${head_ref/\//-}"
          ref_name="${head_ref:-zbmed-dev}"
          ref_name="${ref_name#v}"
          echo "imageTag=$ref_name" >> "$GITHUB_OUTPUT"

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and publish Docker image
        run: |
           docker build -t ghcr.io/${{ github.repository }}:${{ steps.generate-image-tag.outputs.imageTag }} . -f dockerfiles/Dockerfile.ubuntu
           docker push ghcr.io/${{ github.repository }}:${{ steps.generate-image-tag.outputs.imageTag }}

  deploy:
    needs: build-and-push-image
    if: github.ref == 'refs/heads/zbmed-dev'
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - run: |
        mkdir -p .kube
        echo "${{ env.KUBECONFIG_FILE }}" > $KUBECONFIG
     - uses: stefanprodan/kube-tools@v1
       with:
         helmv3: 3.12.0
         command: |
           kubectl get nodes
           helmv3 repo add skosmos-deployment https://zbmed.github.io/skosmos-deployment/
           helmv3 repo update
           helmv3 upgrade semlookp-skosmos-ui \
           --install \
           --set-json='frontend.image="ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.sha || github.sha }}"' \
           --set-json='ingress.dns="semlookp-skosmos.qa.km.k8s.zbmed.de"' \
           --set-json='backend.releaseName="semlookp-skosmos"' \
           --set-json='ingress.path="/"' \
           skosmos-deployment/skosmos-ui