name: Deployment to production
concurrency: production
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: "Name of the Docker image"
        required: true
        type: string
env:
  KUBECONFIG: .kube/config
  KUBECONFIG_FILE: ${{ secrets.KUBECONFIG_PROD }}
  IMAGE_NAME: ${{ github.event.inputs.image_name }}
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p .kube
          echo "${{ env.KUBECONFIG_FILE }}" > $KUBECONFIG
      - uses: stefanprodan/kube-tools@v1
        with:
          helmv3: 3.12.0
          command: |
            helmv3 repo add skosmos-deployment https://zbmed.github.io/skosmos-deployment/
            helmv3 repo update
            helmv3 upgrade semlookp-skosmos-ui \
            --install \
            --namespace='zbmed-ts-nfdi4cat' \
            --set-json='frontend.image="ghcr.io/${{ github.repository }}:${{ github.event.pull_request.head.sha || github.sha }}"' \
            --set-json='ingress.dns="semanticlookup.zbmed.de"' \
            --set-json='backend.releaseName="semlookp-skosmos"' \
            --set-json='ingress.path="/skosmos(/|$)(.*)"' \
            --set-json='ingress.pathType="ImplementationSpecific"' \
            --set-json='ingress.appRoot="/skosmos"' \
            --set-json='ingress.rewriteTarget="/$2"' \
            --set ingress.enableSSL="true" \
            --set ingress.certIssuer="letsencrypt-prod" \
            skosmos-deployment/skosmos-ui